### ISSUE TITLE
Hard-coded gas price may not be enough for some blockchains

### ISSUE THREAD

**Issue by tab00** [Zoltu/deterministic-deployment-proxy#18]
Some blockchains have market gas prices usually above 100 gwei, e.g. Polygon: https://polygonscan.com/gastracker

Since this CREATE2 factory contract has a gas price of 100 gwei hard coded in the raw transaction, does this mean that it would not be deployable on a blockchain as long as its market gas prices stay above 100 gwei? Or are there some ways around to still deploy it?

**Comment by MicahZoltu** [comment]
This is correct.  You will need to wait until the baseFee drops below 100 (for chains with dynamic gas prices), or you will need a friendly block builder to accept out-of-band payment for inclusion if there is no on-chain marketplace.  Alternatively, just wait until the gas price drops below 100 if that is something that happens periodically.

Another option is to get the contract included in a hard fork.  Some blockchains have done this for this contract because they don't support legacy transactions at all.

**Comment by drortirosh** [comment]
> Some blockchains have done this for this contract because they don't support legacy transactions at all.

Do you have specific blockchains that did include it with a fork?

**Comment by MicahZoltu** [comment]
I believe Optimism did this.  I have hard there are others but I don't know which.
