### ISSUE TITLE
Error: only replay-protected (EIP-155) transactions allowed over 

### ISSUE THREAD

**Issue by leon-do** [Zoltu/deterministic-deployment-proxy#21]
I tried broadcasting the transaction in `output/deployment.json` for another chain that supports EIP-155. Is there a way to support this?

**Comment by MicahZoltu** [comment]
In many cases, there is a flag you can pass to your Ethereum client that overrides the replay-protected transaction limitation.  It depends on the blockchain and the client, but I know go-ethereum client has such a limitation and override flag.  I recommend looking for that.

For having it be part of genesis block, I think you probably need the deployed byte code rather than the deployment bytecode.  You can find that on Etherscan for Ethereum Mainnet at the deployed address and just copy that over to your genesis block deployment.

I'm going to close this issue for now since it isn't anything that can be done in this repository, but I will continue to receive email notifications for it so feel free to reply here with further questions!
